MLmodels
vifraa/datx02-05 pull request #19
Opened 2020-03-29 02:13 UTC by YazanGhafir

* Created MLmodels map, exported Lasso, ridge models as separate model classes
* Implemented ElasticNets, DecisionTrees, RandomForest models. 
* Enhanced the implementation of the models with automatic data loading, result printing and 
* integrated learning curve plotting in all of the models.
* Created Models Runner class that runs all the models or specific models as requested and print the results and plot the curves. 
* Created also Data loader class to centralize the reading of the data, printing it, and integrated implementation of PCA to plot the data points in 2D, to see if there are eventual correlations between the data points.

2020-03-30 07:54 UTC, vifraa requested changes
Överlag väldigt bra! Snyggt jobbat!!!

Drog lite kommentarer på vad som behöver ändras för att det ska kunna användas där viktigaste två är:
1. Klass för data där man kan skicka in X och Y. (Eftersom modellerna kräver ett objekt med datan liggandes på speciell struktur.)
2. Sätt att komma åt den tränade modellen från klassen. Utan detta går det inte att spara ner och användas i recommendation engine.

2020-03-30 07:54 UTC, vifraa commented on models/.gitignore
>  data/
```suggestion

```

2020-03-30 07:54 UTC, vifraa commented on models/.gitignore
>  data/
Fix på merge conflict.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/ModelsRunner.py
> +        pass
Skapa en parameter för att skicka in data som inte är DataSample, likt vad som är gjort på modellerna.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/NeuralNetwork.py
> +        pass
Ej implementerade.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/DataReader.py
> +class DataSample:
Alla modeller använder datan på en viss struktur som implicerar att den måste vara i en klass likt denna. För att man ska kunna trycka in data på ett dynamiskt sätt skapa gärna en klass utöver den här där man som argument i konstruktorn kan skicka in X och Y, och att det enda som klassen sen gör är att shuffla, splitta och spara på objektet för att användningen ska fungera i modeller.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/DecisionTree.py
> +
Måste finnas sätt att komma åt den underliggande tränade modellen för att kunna sparas ner för användning i recommendation engine.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/ElasticNets.py
> +
Måste finnas sätt att komma åt den underliggande tränade modellen för att kunna sparas ner för användning i recommendation engine.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/Lasso.py
> +        lasso.fit(self.data.Xtrain, self.data.Ytrain)
Måste finnas sätt att komma åt den underliggande tränade modellen för att kunna sparas ner för användning i recommendation engine.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/RandomForest.py
> +
Måste finnas sätt att komma åt den underliggande tränade modellen för att kunna sparas ner för användning i recommendation engine.

2020-03-30 07:54 UTC, vifraa commented on models/MLmodels/Ridge.py
> +
Måste finnas sätt att komma åt den underliggande tränade modellen för att kunna sparas ner för användning i recommendation engine.

2020-04-02 19:28 UTC, YazanGhafir commented
All the commens has been resolved and more is added such:

 An object of any class of the models can be instantiated in one of the following ways:

       * using path, ex: Ridge(path=GIVEN_PATH) then the constructor will read
            the data (csv) in the given path however its sized, just that the target is
            the located as the last column, then it partition, shuffle and instantiate the date to:
            self.data.Xtrain, self.data.Ytrain, self.data.Xtest, self.data.Ytest

       * using X and Y ex: Ridge(X=GIVEN_X, Y=GIVEN_Y) then the constructor will
            create data model with the given X and Y and partition it also to:
            self.data.Xtrain, self.data.Ytrain, self.data.Xtest, self.data.Ytest

       * using already partitioned data then the constructor will
            create data model with the given data and partition it also to:
            self.data.Xtrain, self.data.Ytrain, self.data.Xtest, self.data.Ytest

       * if nothing of the above passed as argument ex. Ridge() then
            the constructor will read ready data using the Data_sample class
            in DataReader.py and have it in the same format specified above

2020-04-02 20:37 UTC, merged